Login page design (Resolves #15)
PestoTech/project-class-insights-client pull request #20
Opened 2018-07-13 01:40 UTC by kundanvishen

This PR Resolves #15 
Changes:
**Desktop**:
![image](https://user-images.githubusercontent.com/8252717/42667893-8743b8c8-866b-11e8-82ce-3f5279e726d9.png)
**Tablets**
![image](https://user-images.githubusercontent.com/8252717/42667906-9590a396-866b-11e8-92eb-b3d92cb2e3ee.png)

**Mobile Devices**
![image](https://user-images.githubusercontent.com/8252717/42667921-a5b6cf48-866b-11e8-96cc-cb03512e181c.png)

2018-07-13 10:57 UTC, adityad85 submitted a review, later dismissed

2018-07-13 16:13 UTC, andrewlinfoot requested changes
loving the screenshots in the PR. you should make more components to abstract away your classes. this is super useful for keeping a consistent look across the app. watch this video and refactor: https://www.youtube.com/watch?v=gNeavlJ7lNY

2018-07-13 16:31 UTC, andrewlinfoot commented on src/components/LoginPage/LoginPage.js
> +                          <button
should be a button component

2018-07-13 16:32 UTC, andrewlinfoot commented on src/components/LoginPage/LoginPage.js
> +                              {
would make an `<Error meta={meta} />` component

2018-07-13 16:33 UTC, andrewlinfoot commented on src/components/LoginPage/LoginPage.js
> +                              <input
would make an `Input` component that adds the className "form-control"

2018-07-13 16:38 UTC, kundanvishen commented on src/components/LoginPage/LoginPage.js
> +                          <button
Thanks! Will make the changes 👍

2018-07-15 23:14 UTC, kundanvishen commented
@andrewlinfoot advised changes have been made. Please review.

2018-07-16 15:02 UTC, andrewlinfoot requested changes

2018-07-16 15:02 UTC, andrewlinfoot commented on src/components/RegisterPage/RegisterPage.js
>                        {meta.error && meta.touched && (
Use the FormError component here

2018-07-16 15:02 UTC, andrewlinfoot commented on src/components/RegisterPage/RegisterPage.js
> +                        <span>
And here

2018-07-16 15:02 UTC, andrewlinfoot commented on src/components/RegisterPage/RegisterPage.js
> +                        <span>
And here

2018-07-16 15:51 UTC, kundanvishen commented
@andrewlinfoot I should not have added RegisterPage component to this PR 👎 
Everything related to RegisterPage would be handled in RegsiterPage Design PR.
Would a blank RegisterPage component work for now?

2018-07-16 15:58 UTC, andrewlinfoot commented
Awh got it, LGTM then

2018-07-16 15:58 UTC, andrewlinfoot approved these changes

2018-07-16 16:00 UTC, merged