Application theming and styling
PestoTech/project-class-insights-client pull request #26
Opened 2018-07-17 00:58 UTC by kundanvishen

This PR resolves #25

**Tablet:**
<img width="1136" alt="screen shot 2018-07-17 at 6 24 14 am" src="https://user-images.githubusercontent.com/8252717/42790793-82524fd8-898a-11e8-8c1e-b04613522388.png">

**Mobile:**
<img width="470" alt="screen shot 2018-07-17 at 6 24 28 am" src="https://user-images.githubusercontent.com/8252717/42790794-82a50764-898a-11e8-861a-2f21f0bc1e49.png">

**Desktop:**
<img width="1440" alt="screen shot 2018-07-17 at 6 26 43 am" src="https://user-images.githubusercontent.com/8252717/42790795-8323a74a-898a-11e8-8c97-ba66726a6864.png">

2018-07-17 19:03 UTC, ArfatSalman requested changes

2018-07-17 19:03 UTC, ArfatSalman commented on src/App/App.css
> +  /* background: #444c67 !important; */
No comments!

2018-07-17 19:03 UTC, ArfatSalman commented on src/App/App.css
> +  background: #e6a1f2 !important;
Why so many !important?

2018-07-17 19:04 UTC, ArfatSalman commented
Also, it'd be a good idea to start creating abstractions of your component with in-built styles. But move fast too.

2018-07-17 21:53 UTC, kundanvishen commented
Would definitely create the abstractions for components from next PR 👍🏻

2018-07-17 22:01 UTC, kundanvishen commented
@ArfatSalman Made the changes, please merge.

2018-07-18 17:40 UTC, ArfatSalman approved these changes

2018-07-18 17:41 UTC, merged