[Chore]: Added the travis.yml for CI
PestoTech/project-class-insights-client pull request #9
Opened 2018-07-03 21:48 UTC by adityad85

2018-07-03 21:50 UTC, ArfatSalman requested changes
Why the CI is failing?

Add a test file and `test` script in your `package.json`.

2018-07-03 22:12 UTC, ArfatSalman requested changes
You also need to set the `test` script in the `package.json`.


Also, 

```js
import React from 'react';
import Enzyme, {shallow} from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({adapter: new Adapter()});

import CheckboxWithLabel from '../CheckboxWithLabel';

it('CheckboxWithLabel changes the text after click', () => {
  // Render a checkbox with label in the document
  const checkbox = shallow(
    <CheckboxWithLabel labelOn="On" labelOff="Off" />
);

  expect(checkbox.text()).toEqual('Off');

  checkbox.find('input').simulate('change');

  expect(checkbox.text()).toEqual('On');
});
```

Use an actual test case. Your `App.js` is already exporting a component. Test it.

2018-07-04 18:23 UTC, anshurathee commented on package.json
> +  "jest": {
Have a separate jest.config file in the root of the project and place all the configurations in that file.
http://jestjs.io/docs/en/configuration

2018-07-04 18:25 UTC, anshurathee requested changes

2018-07-04 18:25 UTC, anshurathee commented on package.json
> +  "jest": {
Make a separate jest.config.js file in the root of the repo. Code all the configurations there.
http://jestjs.io/docs/en/configuration

2018-07-04 18:32 UTC, anshurathee commented on package.json
> +  "lint-staged": {
Similarly move the lint-staged config to a .lintstagedrc file

2018-07-04 21:48 UTC, anshurathee approved these changes

2018-07-04 22:55 UTC, ArfatSalman approved these changes

2018-07-04 22:55 UTC, merged